// Classificação e parâmetros conferidos no catálogo Ordem Paranormal do C.R.I.S., 02/10/2026.
// Resumos próprios: consulte o livro para o texto integral e exceções de cada efeito.
(function (scope) {
    "use strict";
    const elements = Object.freeze(["Conhecimento", "Energia", "Morte", "Sangue", "Medo", "Varia"]);
    const choices = Object.freeze(elements.slice(0, 4));
    const costs = Object.freeze({ 1: 1, 2: 3, 3: 6, 4: 10 });
    const rows = [];
    const normalize = text => String(text || "").normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLocaleLowerCase("pt-BR");
    const slug = text => normalize(text).replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    const v = (extraCost, description, minCircle = null, affinity = false) => Object.freeze({ extraCost, description, minCircle, affinity });
    function group(element, entries) {
        entries.forEach(([name, circle, range, target, duration, description, discente = null, verdadeiro = null, options = {}]) => {
            rows.push(Object.freeze({ id: slug(name), name, element, circle, cost: costs[circle],
                book: "Ordem Paranormal", source: "https://crisordemparanormal.com/",
                execution: options.execution || "padrão", range, target, duration,
                resistance: options.resistance || "Não indicada", requirements: options.requirements || "",
                description, versions: Object.freeze({ normal: v(0, description), ...(discente ? { discente } : {}), ...(verdadeiro ? { verdadeiro } : {}) }) }));
        });
    }
    group("Conhecimento", [
        ["Alterar Memória", 3, "toque", "1 pessoa", "instantânea", "Modifica detalhes ou apaga memórias da última hora; elas retornam em 1d4 dias.", null, v(4, "Pode atingir memórias das últimas 24 horas.", 4), { resistance: "Vontade anula" }],
        ["Aprimorar Mente", 2, "toque", "1 ser", "cena", "Concede +1 em INT ou PRE, sem aumentar PE ou perícias treinadas.", v(3, "O aumento de atributo passa a +2.", 3), v(7, "O aumento de atributo passa a +3.", 4, true)],
        ["Compreensão Paranormal", 1, "toque", "1 ser ou objeto", "cena", "Permite compreender idiomas humanos, comunicar-se com pessoas ou perceber emoções básicas de animais; não traduz sigilos.", v(2, "Alcance curto e alvos escolhidos.", 2), v(5, "Pessoal: permite falar, escrever e compreender qualquer idioma humano.", 3), { resistance: "Vontade anula" }],
        ["Contato Paranormal", 3, "pessoal", "você", "1 dia", "Recebe seis d6 para somar a testes de perícia. Cada resultado 6 custa 2 SAN; termina sem dados ou com SAN 0.", v(4, "Usa d8; cada 8 custa 3 SAN.", 4), v(9, "Usa d12; cada 12 custa 5 SAN.", 4, true), { execution: "completa" }],
        ["Controle Mental", 4, "médio", "1 pessoa ou animal", "sustentada", "Controla o alvo sem ordens suicidas. Vontade ao fim de cada turno pode libertá-lo; resistir deixa-o pasmo por 1 rodada.", v(5, "Pode afetar até cinco pessoas ou animais."), v(10, "Pode afetar até dez pessoas ou animais.", null, true), { resistance: "Vontade parcial" }],
        ["Detecção de Ameaças", 2, "pessoal", "esfera de 18m de raio", "cena", "Sente seres hostis e armadilhas na área. Movimento e Percepção DT 20 revelam direção e distância.", v(3, "Não fica desprevenido contra perigos detectados e ganha +5 em resistências contra armadilhas.", 3), v(5, "Mantém os benefícios discentes por 1 dia.", 4)],
        ["Enfeitiçar", 1, "curto", "1 pessoa", "cena", "Torna o alvo prestativo e concede +10 em Diplomacia com ele. Hostilidade encerra o efeito; alvos hostis ou em combate resistem com +5.", v(2, "Substitui o efeito por uma sugestão aceitável, cumprida pelo alvo.", 2), v(5, "Afeta todos os alvos no alcance.", 3), { resistance: "Vontade anula" }],
        ["Esconder dos Olhos", 2, "pessoal", "você", "1 rodada", "Invisibilidade com camuflagem total e Furtividade +15; ataques ou ações hostis encerram o efeito.", v(3, "Sustentada: esfera móvel de 3m torna você e aliados invisíveis; ações hostis ainda revelam o autor.", 3), v(7, "Padrão, toque, 1 ser, sustentada. Ações hostis não encerram a invisibilidade.", 4, true), { execution: "livre" }],
        ["Inexistir", 4, "toque", "1 ser", "instantânea", "Causa 10d12+10 de Conhecimento; resistência reduz a 2d12 e debilitado por 1 rodada. Reduzido a 0 PV, o alvo é apagado.", v(5, "Dano 15d12+15; resistido 3d12."), v(10, "Dano 20d12+20; resistido 4d12.", null, true), { resistance: "Vontade parcial" }],
        ["Invadir Mente", 2, "médio ou toque", "1 ser ou 2 pessoas voluntárias", "instantânea ou 1 dia", "Escolhe rajada de 6d6 Conhecimento e atordoamento por 1 rodada, ou ligação telepática entre duas pessoas. Resistir reduz dano e evita atordoamento, limitado a uma vez por cena.", v(3, "Rajada 10d6; ligação permite usar os sentidos do alvo com movimento, podendo ser suprimida por Vontade.", 3), v(7, "Rajada 10d6 em seres escolhidos; ligação entre até cinco pessoas.", 4), { resistance: "Vontade parcial ou nenhuma" }],
        ["Localização", 2, "pessoal", "círculo de 90m de raio", "cena", "Indica direção e distância da pessoa ou objeto procurado mais próximo; imagem específica deve ser fiel. Chumbo bloqueia a busca.", v(3, "Toque em 1 pessoa: por 1 hora, indica a rota direta para entrar ou sair de um lugar."), v(7, "A área de busca passa a 1km de raio.", 4)],
        ["Mergulho Mental", 3, "toque", "1 pessoa", "sustentada", "Enquanto toca o alvo, fica desprevenido e pode obter uma resposta verdadeira de sim/não por turno se ele falhar em Vontade.", null, v(4, "Execução de 1 dia, alcance ilimitado; exige cuba de ouro com água, máscara categoria II, informação e objeto ou foto do alvo.", 4), { resistance: "Vontade parcial" }],
        ["Ouvir os Sussurros", 1, "pessoal", "você", "instantânea", "Consulta o mestre sobre uma ação da cena: resposta de sim/não/sim e não. Em 1d6, um 1 gera um não enganoso; repetir o assunto mantém o resultado.", v(2, "Execução de 1 minuto: recebe pistas sobre um evento até 1 dia no futuro; falha não responde.", 2), v(5, "Execução de 10 minutos, dura 5 rodadas com uma pergunta por rodada; falha responde ninguém sabe.", 3), { execution: "completa" }],
        ["Perturbação", 1, "curto", "1 pessoa", "1 rodada", "Um alvo que ouve a ordem deve fugir, largar itens, ficar pasmo, sentar-se ou aproximar-se, conforme o comando.", v(2, "Afeta 1 ser e permite Sofra: 3d8 Conhecimento e abalado por 1 rodada."), v(5, "Pode atingir até cinco seres ou ordenar um ataque contra outro alvo em alcance médio.", 3, true), { resistance: "Vontade anula" }],
        ["Possessão", 4, "longo", "1 pessoa viva ou morta", "1 dia", "Assume outro corpo usando seus atributos físicos e deslocamento. Retornar é livre; uma morte pode prender a mente sobrevivente no novo corpo.", null, null, { resistance: "Vontade anula" }],
        ["Tecer Ilusão", 1, "médio", "ilusão de até 4 cubos de 1,5m", "cena", "Cria imagens ou sons simples sem dano; sair do alcance dissipa a ilusão.", v(2, "Até oito cubos, sustentada: combina sentidos e permite mover/alterar a ilusão; ainda não causa dano.", 2), v(5, "Ilusão de perigo: falhar em Vontade causa 6d6 Conhecimento por rodada; dois sucessos seguidos anulam o efeito.", 3), { resistance: "Vontade desacredita" }],
        ["Terceiro Olho", 1, "pessoal", "você", "cena", "Enxerga auras em alcance longo, identificando elemento e intensidade. Movimento identifica poderes e capacidade ritualística de um ser em alcance médio.", v(2, "A duração passa a 1 dia."), v(5, "Também revela seres e objetos invisíveis como formas translúcidas.")],
        ["Vidência", 3, "ilimitado", "1 ser", "5 rodadas", "Observa o alvo e 6m ao redor por superfície reflexiva. Familiaridade altera Vontade (+10 a −10); dois sucessos seguidos encerram e dão imunidade por uma semana.", null, null, { execution: "completa", resistance: "Vontade anula" }]
    ]);
    group("Energia", [
        ["Alterar Destino", 4, "pessoal", "você", "instantânea", "Concede +15 em uma resistência ou na Defesa contra um ataque.", null, v(5, "Alcance curto: beneficia um aliado escolhido."), { execution: "reação" }],
        ["Amaldiçoar Tecnologia", 1, "toque", "1 acessório ou arma de fogo", "cena", "O item recebe uma modificação escolhida temporariamente.", v(2, "Concede duas modificações.", 2), v(5, "Concede três modificações.", 3, true)],
        ["Chamas do Caos", 2, "curto", "arma, objeto ou chama", "cena", "Escolhe: arma causa +1d6 fogo; aquecer objeto causa 1d6 fogo/rodada; extinguir chama gera fumaça; mover chama 9m pode causar 3d6 fogo.", v(3, "Sustentada: movimento uma vez por rodada projeta 4d6 Energia em alvo curto; Reflexos reduz à metade."), v(7, "Como discente, com 8d6 Energia.", 3)],
        ["Coincidência Forçada", 1, "curto", "1 ser", "cena", "Concede +2 nos testes de perícia do alvo.", v(2, "Afeta aliados escolhidos.", 2), v(5, "Afeta aliados escolhidos com bônus +5.", 3, true)],
        ["Contenção Fantasmagórica", 2, "médio", "1 ser", "cena", "Três laços agarram o alvo, inclusive incorpóreo. Cada laço: Defesa 10, PV 10, RD 5, imune a Energia; Atletismo pode romper laços.", v(3, "Seis laços distribuídos com no mínimo dois por alvo.", 3), v(5, "Como discente; cada laço rompido causa 2d6+2 Energia ao alvo preso.", 3, true), { resistance: "Reflexos anula" }],
        ["Convocação Instantânea", 3, "ilimitado", "1 objeto de até 2 espaços", "instantânea", "Traz à mão um objeto marcado previamente. Por 1 hora, movimento pode devolvê-lo; quem o segura pode resistir, revelando sua localização.", v(4, "Permite um objeto de até dez espaços."), v(9, "Recipiente Médio com até dez espaços fica oculto no Outro Lado e é convocado com padrão; exige miniatura categoria II e perde 1 PE máximo permanentemente."), { resistance: "Vontade anula" }],
        ["Deflagração de Energia", 4, "pessoal", "explosão de 15m de raio", "Não indicada", "Exceto o conjurador, todos sofrem (3d10) × 10 Energia e tecnologia quebra. Resistir reduz dano à metade e restaura itens após 1d4 rodadas.", null, v(5, "Afeta somente alvos escolhidos."), { execution: "completa", resistance: "Fortitude parcial" }],
        ["Dissonância Acústica", 2, "médio", "esfera de 6m de raio", "sustentada", "A área deixa seres surdos e impede conjuração de rituais.", v(1, "Um objeto emana silêncio de 3m de raio; posse involuntária permite Vontade para anular."), v(3, "Dura a cena: som não sai da área, mas falar, ouvir e conjurar dentro dela continua possível.", 3)],
        ["Eletrocussão", 1, "curto", "1 ser ou objeto", "instantânea", "Causa 3d6 eletricidade e vulnerável por 1 rodada. Resistir reduz dano e evita condição; eletrônicos sofrem dano dobrado sem resistência.", v(2, "Linha de 30m: 6d6 Energia em seres e objetos livres.", 2), v(5, "Relâmpagos atingem alvos escolhidos com 8d6 Energia cada.", 3), { resistance: "Fortitude parcial" }],
        ["Embaralhar", 1, "pessoal", "você", "cena", "Três cópias concedem Defesa +6. Cada ataque que erra destrói uma e reduz o bônus em 2; depende da visão do atacante.", v(2, "Cinco cópias, Defesa +10.", 2), v(5, "Oito cópias, Defesa +16; destruir cópia ofusca o atacante por 1 rodada.", 3)],
        ["Luz", 1, "curto", "1 objeto", "cena", "Objeto ilumina 9m de raio sem calor; escondê-lo interrompe a luz.", v(2, "Quatro esferas em alcance longo, móveis por ação livre, iluminam 6m cada e podem ofuscar/revelar silhuetas.", 2), v(5, "Na área, aliados ganham +1d20 em Vontade e inimigos ficam ofuscados.", 3), { resistance: "Vontade anula" }],
        ["Polarização Caótica", 1, "curto", "você", "sustentada", "Atrai objeto metálico de até dois espaços com movimento ou concede resistência 5 a balístico, corte, impacto e perfuração.", v(2, "Arremessa até dez objetos/ dez espaços; dano depende do material e peso, com Reflexos para reduzir. Vontade evita arremesso involuntário."), v(5, "Alcance médio: movimento levita e move ser/objeto de até dez espaços por 9m; Vontade pode anular."), { resistance: "Vontade anula" }],
        ["Salto Fantasma", 3, "médio", "você", "instantânea", "Teleporta para local já observado sem precisar de linha de efeito; não age no restante do turno nem surge em matéria sólida.", v(2, "Reação: salto de 1,5m concede +10 Defesa e Reflexos contra ataque ou efeito iminente."), v(4, "Alcance longo: leva até dois seres voluntários tocados.")],
        ["Sopro do Caos", 2, "médio", "área variável", "sustentada", "Manipula vento: levita alvo Médio, empurra em cone de 4,5m usando Ocultismo ou altera a força do vento; requer ações para manter/mover.", v(3, "Pode afetar alvos Grandes."), v(9, "Pode afetar alvos Enormes."), { resistance: "Conforme o efeito" }],
        ["Tela de Ruído", 2, "pessoal", "você", "cena", "Concede 30 PV temporários contra balístico, corte, impacto e perfuração. Alternativa: reação concede RD 15 contra um único dano.", v(3, "PV temporários 60 ou RD 30 na reação."), v(7, "Alcance curto: esfera imóvel aprisiona ser/objeto Enorme ou menor e bloqueia passagem de seres, objetos e dano; Reflexos evita prisão.", 4)],
        ["Teletransporte", 4, "toque", "até 5 seres voluntários", "instantânea", "Transporta até 1.000km. Ocultismo DT 25/30/35 conforme familiaridade; falha desvia o destino e falha por 5 impede transporte, gasta PE e atordoa.", null, v(5, "O destino pode ser qualquer local na Terra.")],
        ["Transfigurar Água", 3, "longo", "esfera de 30m de raio", "cena", "Congela, derrete, eleva, evapora ou baixa água. Evaporar causa 5d8 Energia (dobro contra Morte); enchente pode dar +6m à embarcação.", null, v(5, "Enchente concede +12m; evaporar causa 10d8."), { resistance: "Conforme o efeito" }],
        ["Transfigurar Terra", 3, "longo", "9 cubos de 1,5m", "instantânea", "Amolece, modela ou solidifica terreno. Desabamento causa 10d6 impacto; pode criar cobertura ou prender pés, com Atletismo para escapar.", v(3, "Afeta quinze cubos de 1,5m."), v(7, "Também pode afetar minerais e metais.", 4), { resistance: "Conforme o efeito" }]
    ]);
    group("Morte", [
        ["Âncora Temporal", 3, "curto", "1 ser", "cena", "Falhar em Vontade no início do turno impede deslocamento, mas não ações; dois sucessos seguidos encerram.", null, v(4, "Afeta seres escolhidos.", 4), { resistance: "Vontade parcial" }],
        ["Barganha Insana", 3, "pessoal", "você", "instantânea", "Restaura todos os PV/PE e remove condições negativas. Ao fim da cena, perde 1d4 SAN permanentemente.", null, null, { execution: "completa" }],
        ["Cicatrização", 1, "toque", "1 ser", "instantânea", "Cura 3d8+3 PV e envelhece o alvo em um ano.", v(2, "Cura 5d8+5 PV.", 2), v(9, "Alcance curto, seres escolhidos: cura 7d8+7 PV.", 4, true)],
        ["Consumir Manancial", 1, "pessoal", "você", "instantânea", "Ganha 3d6 PV temporários até o fim da cena.", v(2, "Ganha 6d6 PV temporários.", 2), v(5, "Esfera de 6m: causa 3d6 Morte em seres vivos (Fortitude metade), ganhando PV temporários iguais ao dano total.", 3, true)],
        ["Convocar o Algoz", 4, "1,5m", "1 pessoa", "sustentada", "Algoz incorpóreo avança 12m por turno. Vontade evita abalado; adjacente, falhar em Fortitude zera PV, sucesso causa 6d6 Morte sem baixar de 1 PV.", null, null, { resistance: "Vontade parcial; Fortitude parcial" }],
        ["Decadência", 1, "toque", "1 ser", "instantânea", "Causa 2d8+2 Morte.", v(2, "Faz ataque corpo a corpo com arma na execução; acerto soma 3d8+3 Morte ao dano da arma, sem resistência."), v(5, "Explosão pessoal de 6m causa 8d8+8 Morte.", 3), { resistance: "Fortitude reduz à metade" }],
        ["Definhar", 1, "curto", "1 ser", "cena", "Deixa fatigado; resistir troca por vulnerável.", v(2, "Deixa exausto, ou fatigado ao resistir.", 2), v(5, "Como discente, atingindo até cinco seres.", 3, true), { resistance: "Fortitude parcial" }],
        ["Desacelerar Impacto", 2, "curto", "1 ser ou objetos até 10 espaços", "até o solo ou fim da cena", "Reduz queda a 18m/rodada, evitando dano. Projétil afetado causa metade do dano; não freia golpes ou mergulhos controlados.", v(3, "Afeta seres/objetos somando até cem espaços."), null, { execution: "reação" }],
        ["Distorção Temporal", 4, "pessoal", "bolsão temporal", "3 rodadas", "Age num bolsão temporal sem se deslocar ou interagir externamente. Efeitos duradouros iniciados nele só atingem o exterior após seu término."],
        ["Eco Espiral", 2, "curto", "1 ser", "2 rodadas", "No turno seguinte, padrão concentra; no segundo, padrão descarrega dano de Morte igual ao sofrido pelo alvo na rodada de concentração. Omitir ação dissipa.", v(3, "Afeta até cinco seres."), v(7, "Até três rodadas, com duas de concentração antes da descarga.", 4, true), { resistance: "Fortitude reduz à metade" }],
        ["Espirais da Perdição", 1, "curto", "1 ser", "cena", "Aplica −1d20 nos testes de ataque do alvo.", v(2, "Penalidade passa a −2d20.", 2), v(8, "Penalidade −2d20 em seres escolhidos.", 3)],
        ["Fim Inevitável", 4, "extremo", "vácuo de 1,5m de diâmetro", "4 rodadas", "Seres a até 90m podem cair e ser puxados 30m/rodada; tocar o vácuo no início do turno causa 100 Morte. Segurar apoio concede +5 na resistência.", v(5, "Dura cinco rodadas e não afeta o conjurador.", null, true), v(10, "Dura seis rodadas e poupa seres escolhidos.", null, true), { execution: "completa", resistance: "Fortitude parcial" }],
        ["Miasma Entrópico", 2, "médio", "nuvem de 6m de raio", "instantânea", "Causa 4d8 químico e enjoado por 1 rodada; resistência reduz dano e evita condição.", v(3, "Dano passa a 6d8 Morte."), v(7, "Dura três rodadas; iniciar turno na área causa o dano novamente.", 3), { resistance: "Fortitude parcial" }],
        ["Nuvem de Cinzas", 1, "curto", "nuvem de 6m de raio e altura", "cena", "Camuflagem a 1,5m e total a partir de 3m. Vento forte dissipa em quatro rodadas, vendaval em uma; não funciona sob água.", v(2, "Seres escolhidos enxergam através da nuvem.", 2), v(5, "Na nuvem, deslocamento cai a 3m e ataques sofrem −2.", 3)],
        ["Paradoxo", 2, "médio", "esfera de 6m de raio", "instantânea", "Causa 6d6 Morte nos seres da área.", v(3, "Cena: esfera de 1,5m causa 4d6 Morte uma vez por rodada por ser; movimento desloca esfera 9m."), v(7, "Dano 13d6; alvo reduzido a 0 PV pode virar cinzas e morrer se falhar em Fortitude.", 4), { resistance: "Fortitude reduz à metade" }],
        ["Poeira da Podridão", 3, "médio", "nuvem de 6m de raio", "sustentada", "Na conjuração e início de seus turnos, área sofre 4d8 Morte; falhar em resistência também impede recuperar PV por 1 rodada.", null, v(4, "Dano passa a 4d8+16."), { resistance: "Fortitude reduz à metade" }],
        ["Tentáculos de Lodo", 3, "médio", "círculo de 6m de raio", "cena", "Ocultismo faz manobras de agarrar na conjuração e em seus turnos. Já agarrados sofrem 4d6, metade impacto/metade Morte. Área é terreno difícil.", null, v(5, "Área de 9m de raio e dano 6d6.")],
        ["Velocidade Mortal", 2, "curto", "1 ser", "sustentada", "Concede uma ação de movimento extra por turno; a ação extra não conjura rituais.", v(3, "Troca a ação extra por uma ação padrão, ainda sem conjurar rituais."), v(7, "Afeta alvos escolhidos.", 4, true)],
        ["Zerar Entropia", 3, "curto", "1 pessoa", "cena", "Paralisa, ou deixa lento ao resistir. Ação completa no início do turno permite nova Vontade para encerrar.", v(4, "Pode afetar 1 ser.", 4), v(11, "Afeta seres escolhidos.", 4), { resistance: "Vontade parcial" }]
    ]);
    group("Sangue", [
        ["Aprimorar Físico", 2, "toque", "1 ser", "cena", "Concede +1 em AGI ou FOR, escolhido pelo alvo.", v(3, "O aumento passa a +2.", 3), v(7, "O aumento passa a +3.", 4, true)],
        ["Arma Atroz", 1, "toque", "1 arma corpo a corpo", "sustentada", "Arma concede +2 no ataque e +1 na margem de ameaça.", v(2, "O bônus no ataque passa a +5.", 2), v(5, "Ataque +5, margem de ameaça +2 e multiplicador de crítico +2.", 3, true)],
        ["Armadura de Sangue", 1, "pessoal", "você", "cena", "Defesa +5, cumulativa com rituais mas não com equipamento.", v(5, "Defesa +10 e resistência 5 a balístico, corte, impacto e perfuração.", 3), v(9, "Defesa +15 e resistência 10 aos mesmos tipos.", 4, true)],
        ["Capturar o Coração", 4, "curto", "1 pessoa", "cena", "Obcecado pelo conjurador, o alvo tenta ajudá-lo quando falha em Vontade no início do turno; dois sucessos seguidos encerram.", null, null, { resistance: "Vontade parcial" }],
        ["Corpo Adaptado", 1, "toque", "1 pessoa ou animal", "cena", "Protege de calor/frio extremos, permite respirar água ou ar e evita sufocar em fumaça densa.", v(2, "Dura 1 dia."), v(5, "Alcance curto, pessoas ou animais escolhidos."), { resistance: "Vontade parcial; Fortitude parcial (cabeçalho do CRIS)" }],
        ["Descarnar", 2, "toque", "1 ser", "instantânea", "Causa 6d8 (metade corte/Sangue) e hemorragia de 2d8 Sangue por turno falho em Fortitude; dois sucessos estancam. Resistência inicial reduz dano e evita hemorragia.", v(3, "Dano direto 10d8 e hemorragia 4d8.", 3), v(7, "Pessoal, você, sustentada: ataques corpo a corpo somam 4d8 Sangue e causam hemorragia básica.", 3, true), { resistance: "Fortitude parcial" }],
        ["Distorcer Aparência", 1, "pessoal", "você", "cena", "Muda aparência e voz, concedendo +10 em disfarce por Enganação, sem adquirir habilidades ou estatísticas.", v(2, "Alcance curto e 1 ser; involuntário pode anular com Vontade."), v(5, "Como discente, em seres escolhidos.", 3), { resistance: "Vontade desacredita" }],
        ["Ferver Sangue", 3, "curto", "1 ser", "sustentada", "Na conjuração e turnos do alvo, Fortitude falha causa 4d8 Sangue e fraco; sucesso reduz dano e evita condição. Dois sucessos seguidos encerram.", null, v(4, "Afeta seres escolhidos.", 4, true), { resistance: "Fortitude parcial" }],
        ["Flagelo de Sangue", 2, "toque", "1 pessoa", "cena", "Desobedecer à ordem marcada causa 10d6 Sangue e enjoado por rodada; resistência reduz dano e evita condição. Dois sucessos seguidos apagam a marca.", v(3, "Afeta 1 ser, exceto criaturas de Sangue.", 3), v(7, "Como discente, dura 1 dia.", 4, true), { resistance: "Fortitude parcial" }],
        ["Forma Monstruosa", 3, "pessoal", "você", "cena", "Forma Grande, ataque/dano corpo a corpo +5, 30 PV temporários. Não fala/conjura e ataca o ser mais próximo; Vontade permite evitar aliado. Equipamento fica fundido/inacessível.", v(3, "Também concede imunidade a atordoamento, fadiga, sangramento, sono e veneno."), v(9, "Bônus de ataque/dano +10 e 50 PV temporários.", 4, true)],
        ["Fortalecimento Sensorial", 1, "pessoal", "você", "cena", "Concede +1d20 em Investigação, Luta, Percepção e Pontaria.", v(2, "Inimigos também sofrem −1d20 em ataques contra você.", 2), v(5, "Também imuniza contra surpreendido/desprevenido e concede +10 Defesa e Reflexos.", 4, true)],
        ["Hemofagia", 2, "toque", "1 ser", "instantânea", "Causa 6d6 Sangue e recupera PV iguais à metade do dano causado.", v(3, "Ataque corpo a corpo na execução soma dano da arma e ritual, sem resistência; cura metade do total."), v(7, "Pessoal, cena: padrão a cada rodada toca um ser, causando 4d6 Sangue e curando metade do dano.", 4), { resistance: "Fortitude reduz à metade" }],
        ["Invólucro de Carne", 4, "curto", "1 clone seu", "cena", "Cópia com estatísticas e equipamento mundano, sem consciência. Movimento dá ordem; controle ativo deixa seu corpo em transe. Desfaz a 0 PV ou fora do alcance."],
        ["Ódio Incontrolável", 1, "toque", "1 pessoa", "cena", "Ataque/dano corpo a corpo +2 e resistência física 5. Exige atacar por rodada, até aliados; impede ações de concentração e rituais.", v(2, "Agredir permite outro ataque corpo a corpo contra o mesmo alvo."), v(5, "Ataque/dano +5 e sofre metade de balístico, corte, impacto e perfuração.", 3, true)],
        ["Purgatório", 3, "curto", "área de 6m de raio", "sustentada", "Inimigos ficam vulneráveis a dano físico. Tentar sair causa 6d6 Sangue; falhar em Fortitude impede movimento e perde a ação.", null, null, { resistance: "Fortitude parcial" }],
        ["Transfusão Vital", 2, "toque", "1 ser", "instantânea", "Sofre até 30 Sangue para curar o mesmo valor no alvo; não pode baixar seus PV de 1.", v(3, "Pode transferir até 50 PV.", 3), v(7, "Pode transferir até 100 PV.", 4)],
        ["Vínculo de Sangue", 4, "curto", "1 ser", "cena", "Alvo que falha em Fortitude recebe metade do dano que você sofreria. Pode inverter para receber metade do dano dele; voluntários dispensam resistência.", null, null, { resistance: "Fortitude anula" }],
        ["Vomitar Pestes", 3, "médio", "1 enxame Grande, quadrado de 3m", "sustentada", "Enxame adjacente causa 5d12 Sangue em seu espaço ao fim de seus turnos; movimento desloca-o 12m.", v(2, "Falhar em Reflexos também deixa agarrado; padrão e Acrobacia/Atletismo escapam. Mover enxame solta o alvo."), v(5, "Enxame Enorme, cubo de 6m, com voo 18m."), { resistance: "Reflexos reduz à metade" }]
    ]);
    group("Medo", [
        ["Canalizar o Medo", 4, "toque", "1 pessoa", "até descarregar", "Transfere um ritual conhecido de até 3º círculo para uma conjuração básica gratuita. Seus PE máximos diminuem pelo custo até ser usado; avanços usam PE do alvo.", null, null, { requirements: "Poder de trilha de Conduíte em NEX 99%." }],
        ["Cinerária", 1, "curto", "nuvem de 6m de raio", "cena", "Rituais conjurados na névoa têm DT +5.", v(2, "Também reduz em 2 PE os rituais conjurados na névoa."), v(5, "Também maximiza o dano dos rituais conjurados na névoa.")],
        ["Conhecendo o Medo", 4, "toque", "1 pessoa", "cena", "Falhar zera SAN e deixa enlouquecendo; resistir causa 10d6 mental e apavorado por 1 rodada. Insanidade pode transformar o alvo, a critério do mestre.", null, null, { resistance: "Vontade parcial", requirements: "Poder de trilha de Graduado em NEX 99%." }],
        ["Dissipar Ritual", 3, "médio", "1 ser/objeto ou esfera de 3m", "instantânea", "Ocultismo dissipa rituais ativos cuja DT não supera o teste; não desfaz efeitos instantâneos. Pode suprimir item amaldiçoado por 1 dia, com Vontade do portador."],
        ["Lâmina do Medo", 4, "toque", "1 ser", "instantânea", "Falhar em Fortitude zera PV e deixa morrendo; resistir causa 10d8 Medo ignorando resistências e apavorado por 1 rodada. Sobreviventes ficam com ferimento permanente.", null, null, { resistance: "Fortitude parcial", requirements: "Poder de trilha de Lâmina Paranormal em NEX 99%." }],
        ["Medo Tangível", 4, "pessoal", "você", "cena", "Imuniza contra diversas condições, doenças, venenos e dano adicional de críticos/furtivos; dano físico não reduz PV abaixo de 1.", null, null, { requirements: "Poder de trilha de Flagelador em NEX 99%." }],
        ["Presença do Medo", 4, "pessoal", "emanação de 9m de raio", "sustentada", "Na conjuração e em seus turnos, causa 5d8 mental e 5d8 Medo na área. Vontade reduz ambos; falhar atordoa por 1 rodada, uma vez por cena.", null, null, { resistance: "Vontade reduz à metade (texto do efeito)", requirements: "Poder de trilha de Intuitivo em NEX 99%." }],
        ["Proteção contra Rituais", 2, "toque", "1 ser", "cena", "Concede resistência paranormal 5 e +5 em resistências contra rituais e habilidades de criaturas.", v(3, "Afeta até cinco seres tocados.", 3), v(6, "Até cinco seres tocados; resistência paranormal 10 e bônus nas resistências +10.", 4)],
        ["Rejeitar Névoa", 2, "curto", "nuvem de 6m de raio", "cena", "Rituais na área custam +2 PE por círculo e execução sobe um passo. Neutraliza Cinerária, salvo manutenção por ação completa, que neutraliza ambos.", v(2, "Também reduz em 5 a DT de resistência contra rituais da área."), v(5, "Como discente; dano de rituais na névoa é mínimo.")]
    ]);
    group("Varia", [
        ["Amaldiçoar Arma", 1, "toque", "1 arma corpo a corpo ou pacote de munição", "cena", "Ao aprender, escolhe Conhecimento, Energia, Morte ou Sangue. Arma/munição causa +1d6 desse elemento.", v(2, "Dano adicional passa a +2d6.", 2), v(5, "Dano adicional passa a +4d6.", 3, true)]
    ]);
    const catalog = Object.freeze(rows.sort((a, b) => a.name.localeCompare(b.name, "pt-BR")));
    function classification(item) { return `${item.element} · ${item.circle}º círculo · ${item.cost} PE`; }
    function versionRequirements(item, version) {
        return [item.requirements, version.minCircle ? `${version.minCircle}º círculo` : "", version.affinity ? `Afinidade com ${item.element === "Varia" ? "o elemento escolhido" : item.element}` : ""].filter(Boolean).join(" · ") || "Confira acesso e requisitos no livro e com o mestre.";
    }
    function duplicate(item, entries, element = "") {
        if (item.element === "Varia") {
            return entries.some(entry => entry && ((entry.ritualCatalogId === item.id && entry.element === element) || normalize(entry.name) === normalize(`${item.name} (${element})`) || (normalize(entry.name) === normalize(item.name) && (!entry.element || entry.element === element))));
        }
        return entries.some(entry => entry && (entry.ritualCatalogId === item.id || normalize(entry.name) === normalize(item.name)));
    }
    function entry(item, id, element = "", notes = "") {
        if (item.element === "Varia" && !choices.includes(element)) throw new Error("Escolha um elemento para o ritual.");
        const chosen = item.element === "Varia" ? element : item.element;
        const versions = Object.fromEntries(Object.entries(item.versions).map(([key, value]) => [key, { ...value }]));
        return { id, name: `${item.name}${item.element === "Varia" ? ` (${chosen})` : ""}`, ritualCatalogId: item.id,
            group: item.book, element: chosen, circle: item.circle, cost: item.cost,
            execution: item.execution, range: item.range, target: item.target, duration: item.duration, resistance: item.resistance,
            requirements: item.requirements, versions,
            description: [item.description, ...Object.entries(versions).filter(([key]) => key !== "normal").map(([key, value]) => `${key === "discente" ? "Discente" : "Verdadeiro"} (+${value.extraCost} PE): ${value.description}\nRequisitos: ${versionRequirements({ ...item, element: chosen }, value)}`), item.requirements ? `Requisitos: ${item.requirements}` : "", notes ? `Anotações: ${String(notes).slice(0, 300)}` : ""].filter(Boolean).join("\n\n") };
    }
    const api = Object.freeze({ catalog, elements, choices, costs, normalize, classification, versionRequirements, duplicate, entry });
    scope.REAL_RITUAL_CATALOG = api;
    if (typeof module !== "undefined" && module.exports) module.exports = api;
})(typeof window !== "undefined" ? window : globalThis);
