const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const context = vm.createContext({});
vm.runInContext(fs.readFileSync(require("node:path").join(__dirname, "../equipment-rules.js"), "utf8"), context);
const rules = context.REAL_EQUIPMENT_RULES;
for (const expression of ["", "0d6", "1d1", "101d6", "1d1001", "1d6;alert(1)", "2d6+1d8", "1d6/1d8"]) assert.equal(rules.parseDamage(expression), null, expression);
assert.equal(rules.parseDamage("2d8 - 3").bonus, -3);
assert.equal(rules.parseCritical("19/x3").threshold, 19);
assert.equal(rules.parseCritical("19/x3").multiplier, 3);
assert.equal(rules.parseCritical(19).multiplier, 2);
assert.equal(rules.parseCritical("x4").threshold, 20);
for (const critical of ["", 0, 21, "19/x1", "x9", "19xx3"]) assert.equal(rules.parseCritical(critical), null);
const critical = rules.rollDamage(rules.parseDamage("2d6+3"), rules.parseDamage("1d8+2"), 3, 4, () => 0);
assert.equal(critical.dice.length, 6);
assert.equal(critical.extraDice.length, 1, "dano extra não é multiplicado no crítico");
assert.equal(critical.fixed, 9, "bônus fixos não são multiplicados");
assert.equal(critical.total, 16);
assert.equal(rules.rollDamage(rules.parseDamage("1d6-20"), null, 1, 0, () => 0).total, 0);
let values = [0.95, 0, 0.4], index = 0;
const roll = rules.rollTest(3, () => values[index++]);
assert.equal(roll.dice[roll.chosenIndex], 20);
index = 0;
assert.equal(rules.rollTest(0, () => values[index++]).dice.length, 2);
index = 0;
const negative = rules.rollTest(-2, () => values[index++]);
assert.equal(negative.dice[negative.chosenIndex], 1);
assert.equal(rules.rollTest(undefined), null);
assert.equal(rules.twoHands({ catalogId: "katana", hands: "Duas Mãos" }, 5), true);
assert.equal(rules.twoHands({ catalogId: "katana", hands: "Duas Mãos" }, 10), false);
assert.equal(rules.slot({ category: "protecao", catalogId: "escudo" }), "equippedShieldId");
assert.equal(rules.slot({ category: "protecao", catalogId: "protecao-leve" }), "equippedArmorId");
assert.equal(rules.defaults({ damage: "1d6/1d8", hands: "Uma Mão" }).damage, "1d6");
assert.equal(rules.defaults({ damage: "1d6/1d8", hands: "Uma Mão", combat: { hands: "two" } }).damage, "1d8");
assert.equal(rules.defaults({ weaponStyle: "Arma de Fogo" }).damageAttribute, "none");
assert.equal(rules.defaults({ weaponStyle: "Arma de Disparo", catalogId: "arco-composto" }).damageAttribute, "forca");
for (const weapon of require("../equipment-catalog.js").filter((item) => item.inventoryCategory === "armas")) {
    assert.ok(rules.parseDamage(rules.defaults(weapon).damage), `dano do catálogo: ${weapon.name}`);
    assert.ok(rules.parseCritical(weapon.critical), `crítico do catálogo: ${weapon.name}`);
}
console.log("Regras de equipamento: rolagens, dano extra, crítico, atributos e empunhadura: OK");
